# Generated by Django 3.0.4 on 2020-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_cart_qty', models.CharField(choices=[('25', 'Logo'), ('20', 'Clothing'), ('30', 'WebApp'), ('35', 'Advertising'), ('40', 'Illistration'), ('15', 'Packaging')], default='', max_length=50)),
            ],
        ),
    ]
