# Generated by Django 3.0.5 on 2020-04-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_to_cart_form',
        ),
    ]
