# Generated by Django 3.0.5 on 2020-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkoutuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutuserinfo',
            name='user_price_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
