# Generated by Django 3.0.5 on 2020-07-10 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200708_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutuserinfo',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
