# Generated by Django 3.0.5 on 2020-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200712_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutuserinfo',
            name='user_items',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
