# Generated by Django 3.0.5 on 2020-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_title', models.CharField(max_length=50)),
                ('bottle_price', models.IntegerField(max_length=50)),
                ('bottle_img', models.ImageField(blank=True, null=True, upload_to='draft_img')),
            ],
        ),
        migrations.CreateModel(
            name='add_crate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_title', models.CharField(max_length=50)),
                ('crate_price', models.IntegerField(max_length=50)),
                ('crate_img', models.ImageField(blank=True, null=True, upload_to='draft_img')),
            ],
        ),
        migrations.CreateModel(
            name='add_keg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keg_title', models.CharField(max_length=50)),
                ('keg_price', models.IntegerField(max_length=50)),
                ('keg_img', models.ImageField(blank=True, null=True, upload_to='draft_img')),
            ],
        ),
    ]
