# Generated by Django 3.0.5 on 2020-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_bottle',
            name='bottle_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_crate',
            name='crate_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_keg',
            name='keg_price',
            field=models.IntegerField(),
        ),
    ]
