# Generated by Django 3.0.5 on 2020-05-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200516_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_bottle',
            name='bottle_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='add_crate',
            name='crate_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='add_keg',
            name='keg_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
