# Generated by Django 3.0.5 on 2020-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200516_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_bottle',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
