# Generated by Django 3.0.5 on 2020-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_bottle_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_bottle',
            name='bottle_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
