# Generated by Django 3.0.5 on 2020-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200516_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_crate',
            name='crate_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='add_keg',
            name='keg_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
