# Generated by Django 3.0.5 on 2020-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200516_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_bottle',
            name='bottle_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/bottle'),
        ),
        migrations.AlterField(
            model_name='add_crate',
            name='crate_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/crate'),
        ),
        migrations.AlterField(
            model_name='add_keg',
            name='keg_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/keg'),
        ),
    ]
