# Generated by Django 3.0.5 on 2020-06-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200603_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_bottle',
            name='product_type',
            field=models.CharField(choices=[('1', 'Bottle'), ('2', 'Crate'), ('3', 'Keg')], default='', max_length=50),
        ),
    ]
