# Generated by Django 3.0.5 on 2020-06-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_product'),
        ('cart', '0002_auto_20200610_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_bottle',
        ),
    ]
