# Generated by Django 3.0.5 on 2020-06-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_add_bottle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_crate',
        ),
        migrations.DeleteModel(
            name='add_keg',
        ),
    ]
