# Generated by Django 3.0.5 on 2020-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200610_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/product'),
        ),
    ]
