# Generated by Django 3.0.5 on 2020-07-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200610_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='product_price',
            field=models.FloatField(),
        ),
    ]
