# Generated by Django 3.0.5 on 2020-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200708_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
