# Generated by Django 3.0.5 on 2020-07-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200708_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='product_price',
            field=models.FloatField(),
        ),
    ]
