# Generated by Django 3.0.5 on 2020-11-23 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200712_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='product_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
